// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: proto/utility_protobuf.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace UtilityProtobuf {

  /// <summary>Holder for reflection information generated from proto/utility_protobuf.proto</summary>
  public static partial class UtilityProtobufReflection {

    #region Descriptor
    /// <summary>File descriptor for proto/utility_protobuf.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static UtilityProtobufReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Chxwcm90by91dGlsaXR5X3Byb3RvYnVmLnByb3RvEhB1dGlsaXR5X3Byb3Rv",
            "YnVmIjgKDkluaXRSZXFNZXNzYWdlEhgKEGV4cGlyZV90aW1lc3RhbXAYASAB",
            "KAUSDAoEdHlwZRgCIAEoBSIhCg9Jbml0UmVzcE1lc3NhZ2USDgoGc3RhdHVz",
            "GAEgASgFIngKF1Jlc2FtcGxlSW1hZ2VSZXFNZXNzYWdlEhIKCmRlY29kZV9w",
            "aWMYASABKAkSEgoKZW5jb2RlX3BpYxgCIAEoCRIQCghyZV9waWNfeBgDIAEo",
            "BRIQCghyZV9waWNfeRgEIAEoBRIRCgl1bmtub3duXzAYBSABKAUiLAoYUmVz",
            "YW1wbGVJbWFnZVJlc3BNZXNzYWdlEhAKCGVycl9jb2RlGAEgASgFIm0KD1Rl",
            "eHRTY2FuTWVzc2FnZRIUCgx0ZXh0X3NjYW5faWQYASABKAUSEAoIcGljX3Bh",
            "dGgYAiABKAkSEQoJaGF2ZV90ZXh0GAMgASgFEhEKCXVua25vd25fMBgEIAEo",
            "BRIMCgRyYXRlGAUgASgCIs4BChBRUlNjYW5SZXFNZXNzYWdlEhIKCm9yaWdp",
            "bl9waWMYASABKAkSEgoKZGVjb2RlX3BpYxgCIAEoCRIRCgl1bmtub3duXzAY",
            "AyABKAUSFwoPZW5jb2RlX3BpY19kYXRhGAQgASgMEhQKDGVuY29kZV9waWNf",
            "eBgFIAEoBRIUCgxlbmNvZGVfcGljX3kYBiABKAUSEQoJdW5rbm93bl8xGAcg",
            "ASgFEhQKDHRleHRfc2Nhbl9pZBgIIAEoBRIRCgl1bmtub3duXzMYCSABKAUi",
            "1gEKEVFSU2NhblJlc3BNZXNzYWdlEkMKCXFyX3Jlc3VsdBgBIAMoCzIwLnV0",
            "aWxpdHlfcHJvdG9idWYuUVJTY2FuUmVzcE1lc3NhZ2UuUVJTY2FuUmVzdWx0",
            "EhEKCXVua25vd25fMBgCIAEoBRppCgxRUlNjYW5SZXN1bHQSDgoGcmVzdWx0",
            "GAEgASgMEhAKCHVua25vd18wGAIgASgFEhEKCXVua25vd25fMRgDIAEoARIR",
            "Cgl1bmtub3duXzIYBCABKAESEQoJdW5rbm93bl8zGAUgASgFYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::UtilityProtobuf.InitReqMessage), global::UtilityProtobuf.InitReqMessage.Parser, new[]{ "ExpireTimestamp", "Type" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::UtilityProtobuf.InitRespMessage), global::UtilityProtobuf.InitRespMessage.Parser, new[]{ "Status" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::UtilityProtobuf.ResampleImageReqMessage), global::UtilityProtobuf.ResampleImageReqMessage.Parser, new[]{ "DecodePic", "EncodePic", "RePicX", "RePicY", "Unknown0" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::UtilityProtobuf.ResampleImageRespMessage), global::UtilityProtobuf.ResampleImageRespMessage.Parser, new[]{ "ErrCode" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::UtilityProtobuf.TextScanMessage), global::UtilityProtobuf.TextScanMessage.Parser, new[]{ "TextScanId", "PicPath", "HaveText", "Unknown0", "Rate" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::UtilityProtobuf.QRScanReqMessage), global::UtilityProtobuf.QRScanReqMessage.Parser, new[]{ "OriginPic", "DecodePic", "Unknown0", "EncodePicData", "EncodePicX", "EncodePicY", "Unknown1", "TextScanId", "Unknown3" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::UtilityProtobuf.QRScanRespMessage), global::UtilityProtobuf.QRScanRespMessage.Parser, new[]{ "QrResult", "Unknown0" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::UtilityProtobuf.QRScanRespMessage.Types.QRScanResult), global::UtilityProtobuf.QRScanRespMessage.Types.QRScanResult.Parser, new[]{ "Result", "Unknow0", "Unknown1", "Unknown2", "Unknown3" }, null, null, null, null)})
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class InitReqMessage : pb::IMessage<InitReqMessage>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<InitReqMessage> _parser = new pb::MessageParser<InitReqMessage>(() => new InitReqMessage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<InitReqMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::UtilityProtobuf.UtilityProtobufReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public InitReqMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public InitReqMessage(InitReqMessage other) : this() {
      expireTimestamp_ = other.expireTimestamp_;
      type_ = other.type_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public InitReqMessage Clone() {
      return new InitReqMessage(this);
    }

    /// <summary>Field number for the "expire_timestamp" field.</summary>
    public const int ExpireTimestampFieldNumber = 1;
    private int expireTimestamp_;
    /// <summary>
    ///猜的
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int ExpireTimestamp {
      get { return expireTimestamp_; }
      set {
        expireTimestamp_ = value;
      }
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 2;
    private int type_;
    /// <summary>
    ///为1
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as InitReqMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(InitReqMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ExpireTimestamp != other.ExpireTimestamp) return false;
      if (Type != other.Type) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (ExpireTimestamp != 0) hash ^= ExpireTimestamp.GetHashCode();
      if (Type != 0) hash ^= Type.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ExpireTimestamp != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(ExpireTimestamp);
      }
      if (Type != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Type);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ExpireTimestamp != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(ExpireTimestamp);
      }
      if (Type != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Type);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (ExpireTimestamp != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ExpireTimestamp);
      }
      if (Type != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Type);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(InitReqMessage other) {
      if (other == null) {
        return;
      }
      if (other.ExpireTimestamp != 0) {
        ExpireTimestamp = other.ExpireTimestamp;
      }
      if (other.Type != 0) {
        Type = other.Type;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            ExpireTimestamp = input.ReadInt32();
            break;
          }
          case 16: {
            Type = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            ExpireTimestamp = input.ReadInt32();
            break;
          }
          case 16: {
            Type = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class InitRespMessage : pb::IMessage<InitRespMessage>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<InitRespMessage> _parser = new pb::MessageParser<InitRespMessage>(() => new InitRespMessage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<InitRespMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::UtilityProtobuf.UtilityProtobufReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public InitRespMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public InitRespMessage(InitRespMessage other) : this() {
      status_ = other.status_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public InitRespMessage Clone() {
      return new InitRespMessage(this);
    }

    /// <summary>Field number for the "status" field.</summary>
    public const int StatusFieldNumber = 1;
    private int status_;
    /// <summary>
    ///是否初始化成功 WeChatWin.dll并没有处理这个消息
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Status {
      get { return status_; }
      set {
        status_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as InitRespMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(InitRespMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Status != other.Status) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Status != 0) hash ^= Status.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Status != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Status);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Status != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Status);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Status != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Status);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(InitRespMessage other) {
      if (other == null) {
        return;
      }
      if (other.Status != 0) {
        Status = other.Status;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Status = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Status = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class ResampleImageReqMessage : pb::IMessage<ResampleImageReqMessage>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ResampleImageReqMessage> _parser = new pb::MessageParser<ResampleImageReqMessage>(() => new ResampleImageReqMessage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ResampleImageReqMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::UtilityProtobuf.UtilityProtobufReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ResampleImageReqMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ResampleImageReqMessage(ResampleImageReqMessage other) : this() {
      decodePic_ = other.decodePic_;
      encodePic_ = other.encodePic_;
      rePicX_ = other.rePicX_;
      rePicY_ = other.rePicY_;
      unknown0_ = other.unknown0_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ResampleImageReqMessage Clone() {
      return new ResampleImageReqMessage(this);
    }

    /// <summary>Field number for the "decode_pic" field.</summary>
    public const int DecodePicFieldNumber = 1;
    private string decodePic_ = "";
    /// <summary>
    ///解码图片的路径
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string DecodePic {
      get { return decodePic_; }
      set {
        decodePic_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "encode_pic" field.</summary>
    public const int EncodePicFieldNumber = 2;
    private string encodePic_ = "";
    /// <summary>
    ///原始加密图片的路径
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string EncodePic {
      get { return encodePic_; }
      set {
        encodePic_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "re_pic_x" field.</summary>
    public const int RePicXFieldNumber = 3;
    private int rePicX_;
    /// <summary>
    ///图片长
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int RePicX {
      get { return rePicX_; }
      set {
        rePicX_ = value;
      }
    }

    /// <summary>Field number for the "re_pic_y" field.</summary>
    public const int RePicYFieldNumber = 4;
    private int rePicY_;
    /// <summary>
    ///图片宽
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int RePicY {
      get { return rePicY_; }
      set {
        rePicY_ = value;
      }
    }

    /// <summary>Field number for the "unknown_0" field.</summary>
    public const int Unknown0FieldNumber = 5;
    private int unknown0_;
    /// <summary>
    ///未知 一般为1
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Unknown0 {
      get { return unknown0_; }
      set {
        unknown0_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ResampleImageReqMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ResampleImageReqMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (DecodePic != other.DecodePic) return false;
      if (EncodePic != other.EncodePic) return false;
      if (RePicX != other.RePicX) return false;
      if (RePicY != other.RePicY) return false;
      if (Unknown0 != other.Unknown0) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (DecodePic.Length != 0) hash ^= DecodePic.GetHashCode();
      if (EncodePic.Length != 0) hash ^= EncodePic.GetHashCode();
      if (RePicX != 0) hash ^= RePicX.GetHashCode();
      if (RePicY != 0) hash ^= RePicY.GetHashCode();
      if (Unknown0 != 0) hash ^= Unknown0.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (DecodePic.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(DecodePic);
      }
      if (EncodePic.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(EncodePic);
      }
      if (RePicX != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(RePicX);
      }
      if (RePicY != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(RePicY);
      }
      if (Unknown0 != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(Unknown0);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (DecodePic.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(DecodePic);
      }
      if (EncodePic.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(EncodePic);
      }
      if (RePicX != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(RePicX);
      }
      if (RePicY != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(RePicY);
      }
      if (Unknown0 != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(Unknown0);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (DecodePic.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(DecodePic);
      }
      if (EncodePic.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(EncodePic);
      }
      if (RePicX != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(RePicX);
      }
      if (RePicY != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(RePicY);
      }
      if (Unknown0 != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Unknown0);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ResampleImageReqMessage other) {
      if (other == null) {
        return;
      }
      if (other.DecodePic.Length != 0) {
        DecodePic = other.DecodePic;
      }
      if (other.EncodePic.Length != 0) {
        EncodePic = other.EncodePic;
      }
      if (other.RePicX != 0) {
        RePicX = other.RePicX;
      }
      if (other.RePicY != 0) {
        RePicY = other.RePicY;
      }
      if (other.Unknown0 != 0) {
        Unknown0 = other.Unknown0;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            DecodePic = input.ReadString();
            break;
          }
          case 18: {
            EncodePic = input.ReadString();
            break;
          }
          case 24: {
            RePicX = input.ReadInt32();
            break;
          }
          case 32: {
            RePicY = input.ReadInt32();
            break;
          }
          case 40: {
            Unknown0 = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            DecodePic = input.ReadString();
            break;
          }
          case 18: {
            EncodePic = input.ReadString();
            break;
          }
          case 24: {
            RePicX = input.ReadInt32();
            break;
          }
          case 32: {
            RePicY = input.ReadInt32();
            break;
          }
          case 40: {
            Unknown0 = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class ResampleImageRespMessage : pb::IMessage<ResampleImageRespMessage>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ResampleImageRespMessage> _parser = new pb::MessageParser<ResampleImageRespMessage>(() => new ResampleImageRespMessage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ResampleImageRespMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::UtilityProtobuf.UtilityProtobufReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ResampleImageRespMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ResampleImageRespMessage(ResampleImageRespMessage other) : this() {
      errCode_ = other.errCode_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ResampleImageRespMessage Clone() {
      return new ResampleImageRespMessage(this);
    }

    /// <summary>Field number for the "err_code" field.</summary>
    public const int ErrCodeFieldNumber = 1;
    private int errCode_;
    /// <summary>
    ///可能是 一般为0 错误为8
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int ErrCode {
      get { return errCode_; }
      set {
        errCode_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ResampleImageRespMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ResampleImageRespMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ErrCode != other.ErrCode) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (ErrCode != 0) hash ^= ErrCode.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ErrCode != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(ErrCode);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ErrCode != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(ErrCode);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (ErrCode != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ErrCode);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ResampleImageRespMessage other) {
      if (other == null) {
        return;
      }
      if (other.ErrCode != 0) {
        ErrCode = other.ErrCode;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            ErrCode = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            ErrCode = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class TextScanMessage : pb::IMessage<TextScanMessage>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<TextScanMessage> _parser = new pb::MessageParser<TextScanMessage>(() => new TextScanMessage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<TextScanMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::UtilityProtobuf.UtilityProtobufReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TextScanMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TextScanMessage(TextScanMessage other) : this() {
      textScanId_ = other.textScanId_;
      picPath_ = other.picPath_;
      haveText_ = other.haveText_;
      unknown0_ = other.unknown0_;
      rate_ = other.rate_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TextScanMessage Clone() {
      return new TextScanMessage(this);
    }

    /// <summary>Field number for the "text_scan_id" field.</summary>
    public const int TextScanIdFieldNumber = 1;
    private int textScanId_;
    /// <summary>
    ///可能是
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int TextScanId {
      get { return textScanId_; }
      set {
        textScanId_ = value;
      }
    }

    /// <summary>Field number for the "pic_path" field.</summary>
    public const int PicPathFieldNumber = 2;
    private string picPath_ = "";
    /// <summary>
    ///扫描的图片路径
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string PicPath {
      get { return picPath_; }
      set {
        picPath_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "have_text" field.</summary>
    public const int HaveTextFieldNumber = 3;
    private int haveText_;
    /// <summary>
    ///是否有文字
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int HaveText {
      get { return haveText_; }
      set {
        haveText_ = value;
      }
    }

    /// <summary>Field number for the "unknown_0" field.</summary>
    public const int Unknown0FieldNumber = 4;
    private int unknown0_;
    /// <summary>
    ///未知
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Unknown0 {
      get { return unknown0_; }
      set {
        unknown0_ = value;
      }
    }

    /// <summary>Field number for the "rate" field.</summary>
    public const int RateFieldNumber = 5;
    private float rate_;
    /// <summary>
    ///应该是浮点数 图上要是没文字这个字段肯定为0.0
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float Rate {
      get { return rate_; }
      set {
        rate_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as TextScanMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(TextScanMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (TextScanId != other.TextScanId) return false;
      if (PicPath != other.PicPath) return false;
      if (HaveText != other.HaveText) return false;
      if (Unknown0 != other.Unknown0) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Rate, other.Rate)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (TextScanId != 0) hash ^= TextScanId.GetHashCode();
      if (PicPath.Length != 0) hash ^= PicPath.GetHashCode();
      if (HaveText != 0) hash ^= HaveText.GetHashCode();
      if (Unknown0 != 0) hash ^= Unknown0.GetHashCode();
      if (Rate != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Rate);
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (TextScanId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(TextScanId);
      }
      if (PicPath.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(PicPath);
      }
      if (HaveText != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(HaveText);
      }
      if (Unknown0 != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(Unknown0);
      }
      if (Rate != 0F) {
        output.WriteRawTag(45);
        output.WriteFloat(Rate);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (TextScanId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(TextScanId);
      }
      if (PicPath.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(PicPath);
      }
      if (HaveText != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(HaveText);
      }
      if (Unknown0 != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(Unknown0);
      }
      if (Rate != 0F) {
        output.WriteRawTag(45);
        output.WriteFloat(Rate);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (TextScanId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(TextScanId);
      }
      if (PicPath.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(PicPath);
      }
      if (HaveText != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(HaveText);
      }
      if (Unknown0 != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Unknown0);
      }
      if (Rate != 0F) {
        size += 1 + 4;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(TextScanMessage other) {
      if (other == null) {
        return;
      }
      if (other.TextScanId != 0) {
        TextScanId = other.TextScanId;
      }
      if (other.PicPath.Length != 0) {
        PicPath = other.PicPath;
      }
      if (other.HaveText != 0) {
        HaveText = other.HaveText;
      }
      if (other.Unknown0 != 0) {
        Unknown0 = other.Unknown0;
      }
      if (other.Rate != 0F) {
        Rate = other.Rate;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            TextScanId = input.ReadInt32();
            break;
          }
          case 18: {
            PicPath = input.ReadString();
            break;
          }
          case 24: {
            HaveText = input.ReadInt32();
            break;
          }
          case 32: {
            Unknown0 = input.ReadInt32();
            break;
          }
          case 45: {
            Rate = input.ReadFloat();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            TextScanId = input.ReadInt32();
            break;
          }
          case 18: {
            PicPath = input.ReadString();
            break;
          }
          case 24: {
            HaveText = input.ReadInt32();
            break;
          }
          case 32: {
            Unknown0 = input.ReadInt32();
            break;
          }
          case 45: {
            Rate = input.ReadFloat();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  ///当使用图片时发送的是1 2(可为空) 3 7 8 9项
  ///当在截图中框选时发送的是 4 5 6 7 8 9项
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class QRScanReqMessage : pb::IMessage<QRScanReqMessage>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<QRScanReqMessage> _parser = new pb::MessageParser<QRScanReqMessage>(() => new QRScanReqMessage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<QRScanReqMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::UtilityProtobuf.UtilityProtobufReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public QRScanReqMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public QRScanReqMessage(QRScanReqMessage other) : this() {
      originPic_ = other.originPic_;
      decodePic_ = other.decodePic_;
      unknown0_ = other.unknown0_;
      encodePicData_ = other.encodePicData_;
      encodePicX_ = other.encodePicX_;
      encodePicY_ = other.encodePicY_;
      unknown1_ = other.unknown1_;
      textScanId_ = other.textScanId_;
      unknown3_ = other.unknown3_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public QRScanReqMessage Clone() {
      return new QRScanReqMessage(this);
    }

    /// <summary>Field number for the "origin_pic" field.</summary>
    public const int OriginPicFieldNumber = 1;
    private string originPic_ = "";
    /// <summary>
    ///原始图片路径 可选
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string OriginPic {
      get { return originPic_; }
      set {
        originPic_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "decode_pic" field.</summary>
    public const int DecodePicFieldNumber = 2;
    private string decodePic_ = "";
    /// <summary>
    ///解码后的图片路径 可选
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string DecodePic {
      get { return decodePic_; }
      set {
        decodePic_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "unknown_0" field.</summary>
    public const int Unknown0FieldNumber = 3;
    private int unknown0_;
    /// <summary>
    ///未知 可选 一般为0
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Unknown0 {
      get { return unknown0_; }
      set {
        unknown0_ = value;
      }
    }

    /// <summary>Field number for the "encode_pic_data" field.</summary>
    public const int EncodePicDataFieldNumber = 4;
    private pb::ByteString encodePicData_ = pb::ByteString.Empty;
    /// <summary>
    ///某种编码后的图片数据 可选
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString EncodePicData {
      get { return encodePicData_; }
      set {
        encodePicData_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "encode_pic_x" field.</summary>
    public const int EncodePicXFieldNumber = 5;
    private int encodePicX_;
    /// <summary>
    ///编码图片长	可选
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int EncodePicX {
      get { return encodePicX_; }
      set {
        encodePicX_ = value;
      }
    }

    /// <summary>Field number for the "encode_pic_y" field.</summary>
    public const int EncodePicYFieldNumber = 6;
    private int encodePicY_;
    /// <summary>
    ///编码图片宽 可选
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int EncodePicY {
      get { return encodePicY_; }
      set {
        encodePicY_ = value;
      }
    }

    /// <summary>Field number for the "unknown_1" field.</summary>
    public const int Unknown1FieldNumber = 7;
    private int unknown1_;
    /// <summary>
    ///未知 一般为1
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Unknown1 {
      get { return unknown1_; }
      set {
        unknown1_ = value;
      }
    }

    /// <summary>Field number for the "text_scan_id" field.</summary>
    public const int TextScanIdFieldNumber = 8;
    private int textScanId_;
    /// <summary>
    ///可能是
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int TextScanId {
      get { return textScanId_; }
      set {
        textScanId_ = value;
      }
    }

    /// <summary>Field number for the "unknown_3" field.</summary>
    public const int Unknown3FieldNumber = 9;
    private int unknown3_;
    /// <summary>
    ///未知 一般为1
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Unknown3 {
      get { return unknown3_; }
      set {
        unknown3_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as QRScanReqMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(QRScanReqMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (OriginPic != other.OriginPic) return false;
      if (DecodePic != other.DecodePic) return false;
      if (Unknown0 != other.Unknown0) return false;
      if (EncodePicData != other.EncodePicData) return false;
      if (EncodePicX != other.EncodePicX) return false;
      if (EncodePicY != other.EncodePicY) return false;
      if (Unknown1 != other.Unknown1) return false;
      if (TextScanId != other.TextScanId) return false;
      if (Unknown3 != other.Unknown3) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (OriginPic.Length != 0) hash ^= OriginPic.GetHashCode();
      if (DecodePic.Length != 0) hash ^= DecodePic.GetHashCode();
      if (Unknown0 != 0) hash ^= Unknown0.GetHashCode();
      if (EncodePicData.Length != 0) hash ^= EncodePicData.GetHashCode();
      if (EncodePicX != 0) hash ^= EncodePicX.GetHashCode();
      if (EncodePicY != 0) hash ^= EncodePicY.GetHashCode();
      if (Unknown1 != 0) hash ^= Unknown1.GetHashCode();
      if (TextScanId != 0) hash ^= TextScanId.GetHashCode();
      if (Unknown3 != 0) hash ^= Unknown3.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (OriginPic.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(OriginPic);
      }
      if (DecodePic.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(DecodePic);
      }
      if (Unknown0 != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Unknown0);
      }
      if (EncodePicData.Length != 0) {
        output.WriteRawTag(34);
        output.WriteBytes(EncodePicData);
      }
      if (EncodePicX != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(EncodePicX);
      }
      if (EncodePicY != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(EncodePicY);
      }
      if (Unknown1 != 0) {
        output.WriteRawTag(56);
        output.WriteInt32(Unknown1);
      }
      if (TextScanId != 0) {
        output.WriteRawTag(64);
        output.WriteInt32(TextScanId);
      }
      if (Unknown3 != 0) {
        output.WriteRawTag(72);
        output.WriteInt32(Unknown3);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (OriginPic.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(OriginPic);
      }
      if (DecodePic.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(DecodePic);
      }
      if (Unknown0 != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Unknown0);
      }
      if (EncodePicData.Length != 0) {
        output.WriteRawTag(34);
        output.WriteBytes(EncodePicData);
      }
      if (EncodePicX != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(EncodePicX);
      }
      if (EncodePicY != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(EncodePicY);
      }
      if (Unknown1 != 0) {
        output.WriteRawTag(56);
        output.WriteInt32(Unknown1);
      }
      if (TextScanId != 0) {
        output.WriteRawTag(64);
        output.WriteInt32(TextScanId);
      }
      if (Unknown3 != 0) {
        output.WriteRawTag(72);
        output.WriteInt32(Unknown3);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (OriginPic.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(OriginPic);
      }
      if (DecodePic.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(DecodePic);
      }
      if (Unknown0 != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Unknown0);
      }
      if (EncodePicData.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(EncodePicData);
      }
      if (EncodePicX != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(EncodePicX);
      }
      if (EncodePicY != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(EncodePicY);
      }
      if (Unknown1 != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Unknown1);
      }
      if (TextScanId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(TextScanId);
      }
      if (Unknown3 != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Unknown3);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(QRScanReqMessage other) {
      if (other == null) {
        return;
      }
      if (other.OriginPic.Length != 0) {
        OriginPic = other.OriginPic;
      }
      if (other.DecodePic.Length != 0) {
        DecodePic = other.DecodePic;
      }
      if (other.Unknown0 != 0) {
        Unknown0 = other.Unknown0;
      }
      if (other.EncodePicData.Length != 0) {
        EncodePicData = other.EncodePicData;
      }
      if (other.EncodePicX != 0) {
        EncodePicX = other.EncodePicX;
      }
      if (other.EncodePicY != 0) {
        EncodePicY = other.EncodePicY;
      }
      if (other.Unknown1 != 0) {
        Unknown1 = other.Unknown1;
      }
      if (other.TextScanId != 0) {
        TextScanId = other.TextScanId;
      }
      if (other.Unknown3 != 0) {
        Unknown3 = other.Unknown3;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            OriginPic = input.ReadString();
            break;
          }
          case 18: {
            DecodePic = input.ReadString();
            break;
          }
          case 24: {
            Unknown0 = input.ReadInt32();
            break;
          }
          case 34: {
            EncodePicData = input.ReadBytes();
            break;
          }
          case 40: {
            EncodePicX = input.ReadInt32();
            break;
          }
          case 48: {
            EncodePicY = input.ReadInt32();
            break;
          }
          case 56: {
            Unknown1 = input.ReadInt32();
            break;
          }
          case 64: {
            TextScanId = input.ReadInt32();
            break;
          }
          case 72: {
            Unknown3 = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            OriginPic = input.ReadString();
            break;
          }
          case 18: {
            DecodePic = input.ReadString();
            break;
          }
          case 24: {
            Unknown0 = input.ReadInt32();
            break;
          }
          case 34: {
            EncodePicData = input.ReadBytes();
            break;
          }
          case 40: {
            EncodePicX = input.ReadInt32();
            break;
          }
          case 48: {
            EncodePicY = input.ReadInt32();
            break;
          }
          case 56: {
            Unknown1 = input.ReadInt32();
            break;
          }
          case 64: {
            TextScanId = input.ReadInt32();
            break;
          }
          case 72: {
            Unknown3 = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class QRScanRespMessage : pb::IMessage<QRScanRespMessage>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<QRScanRespMessage> _parser = new pb::MessageParser<QRScanRespMessage>(() => new QRScanRespMessage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<QRScanRespMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::UtilityProtobuf.UtilityProtobufReflection.Descriptor.MessageTypes[6]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public QRScanRespMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public QRScanRespMessage(QRScanRespMessage other) : this() {
      qrResult_ = other.qrResult_.Clone();
      unknown0_ = other.unknown0_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public QRScanRespMessage Clone() {
      return new QRScanRespMessage(this);
    }

    /// <summary>Field number for the "qr_result" field.</summary>
    public const int QrResultFieldNumber = 1;
    private static readonly pb::FieldCodec<global::UtilityProtobuf.QRScanRespMessage.Types.QRScanResult> _repeated_qrResult_codec
        = pb::FieldCodec.ForMessage(10, global::UtilityProtobuf.QRScanRespMessage.Types.QRScanResult.Parser);
    private readonly pbc::RepeatedField<global::UtilityProtobuf.QRScanRespMessage.Types.QRScanResult> qrResult_ = new pbc::RepeatedField<global::UtilityProtobuf.QRScanRespMessage.Types.QRScanResult>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::UtilityProtobuf.QRScanRespMessage.Types.QRScanResult> QrResult {
      get { return qrResult_; }
    }

    /// <summary>Field number for the "unknown_0" field.</summary>
    public const int Unknown0FieldNumber = 2;
    private int unknown0_;
    /// <summary>
    ///未知 一般为1
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Unknown0 {
      get { return unknown0_; }
      set {
        unknown0_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as QRScanRespMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(QRScanRespMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!qrResult_.Equals(other.qrResult_)) return false;
      if (Unknown0 != other.Unknown0) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= qrResult_.GetHashCode();
      if (Unknown0 != 0) hash ^= Unknown0.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      qrResult_.WriteTo(output, _repeated_qrResult_codec);
      if (Unknown0 != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Unknown0);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      qrResult_.WriteTo(ref output, _repeated_qrResult_codec);
      if (Unknown0 != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Unknown0);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += qrResult_.CalculateSize(_repeated_qrResult_codec);
      if (Unknown0 != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Unknown0);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(QRScanRespMessage other) {
      if (other == null) {
        return;
      }
      qrResult_.Add(other.qrResult_);
      if (other.Unknown0 != 0) {
        Unknown0 = other.Unknown0;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            qrResult_.AddEntriesFrom(input, _repeated_qrResult_codec);
            break;
          }
          case 16: {
            Unknown0 = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            qrResult_.AddEntriesFrom(ref input, _repeated_qrResult_codec);
            break;
          }
          case 16: {
            Unknown0 = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the QRScanRespMessage message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
      public sealed partial class QRScanResult : pb::IMessage<QRScanResult>
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          , pb::IBufferMessage
      #endif
      {
        private static readonly pb::MessageParser<QRScanResult> _parser = new pb::MessageParser<QRScanResult>(() => new QRScanResult());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<QRScanResult> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::UtilityProtobuf.QRScanRespMessage.Descriptor.NestedTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public QRScanResult() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public QRScanResult(QRScanResult other) : this() {
          result_ = other.result_;
          unknow0_ = other.unknow0_;
          unknown1_ = other.unknown1_;
          unknown2_ = other.unknown2_;
          unknown3_ = other.unknown3_;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public QRScanResult Clone() {
          return new QRScanResult(this);
        }

        /// <summary>Field number for the "result" field.</summary>
        public const int ResultFieldNumber = 1;
        private pb::ByteString result_ = pb::ByteString.Empty;
        /// <summary>
        ///二维码识别结果
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public pb::ByteString Result {
          get { return result_; }
          set {
            result_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        /// <summary>Field number for the "unknow_0" field.</summary>
        public const int Unknow0FieldNumber = 2;
        private int unknow0_;
        /// <summary>
        ///未知 一般为19
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int Unknow0 {
          get { return unknow0_; }
          set {
            unknow0_ = value;
          }
        }

        /// <summary>Field number for the "unknown_1" field.</summary>
        public const int Unknown1FieldNumber = 3;
        private double unknown1_;
        /// <summary>
        ///未知 可能是浮点数
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public double Unknown1 {
          get { return unknown1_; }
          set {
            unknown1_ = value;
          }
        }

        /// <summary>Field number for the "unknown_2" field.</summary>
        public const int Unknown2FieldNumber = 4;
        private double unknown2_;
        /// <summary>
        ///未知 可能是浮点数
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public double Unknown2 {
          get { return unknown2_; }
          set {
            unknown2_ = value;
          }
        }

        /// <summary>Field number for the "unknown_3" field.</summary>
        public const int Unknown3FieldNumber = 5;
        private int unknown3_;
        /// <summary>
        ///未知 一般为1
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int Unknown3 {
          get { return unknown3_; }
          set {
            unknown3_ = value;
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other) {
          return Equals(other as QRScanResult);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(QRScanResult other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (Result != other.Result) return false;
          if (Unknow0 != other.Unknow0) return false;
          if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Unknown1, other.Unknown1)) return false;
          if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Unknown2, other.Unknown2)) return false;
          if (Unknown3 != other.Unknown3) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode() {
          int hash = 1;
          if (Result.Length != 0) hash ^= Result.GetHashCode();
          if (Unknow0 != 0) hash ^= Unknow0.GetHashCode();
          if (Unknown1 != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Unknown1);
          if (Unknown2 != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Unknown2);
          if (Unknown3 != 0) hash ^= Unknown3.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          output.WriteRawMessage(this);
        #else
          if (Result.Length != 0) {
            output.WriteRawTag(10);
            output.WriteBytes(Result);
          }
          if (Unknow0 != 0) {
            output.WriteRawTag(16);
            output.WriteInt32(Unknow0);
          }
          if (Unknown1 != 0D) {
            output.WriteRawTag(25);
            output.WriteDouble(Unknown1);
          }
          if (Unknown2 != 0D) {
            output.WriteRawTag(33);
            output.WriteDouble(Unknown2);
          }
          if (Unknown3 != 0) {
            output.WriteRawTag(40);
            output.WriteInt32(Unknown3);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
          if (Result.Length != 0) {
            output.WriteRawTag(10);
            output.WriteBytes(Result);
          }
          if (Unknow0 != 0) {
            output.WriteRawTag(16);
            output.WriteInt32(Unknow0);
          }
          if (Unknown1 != 0D) {
            output.WriteRawTag(25);
            output.WriteDouble(Unknown1);
          }
          if (Unknown2 != 0D) {
            output.WriteRawTag(33);
            output.WriteDouble(Unknown2);
          }
          if (Unknown3 != 0) {
            output.WriteRawTag(40);
            output.WriteInt32(Unknown3);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(ref output);
          }
        }
        #endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize() {
          int size = 0;
          if (Result.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeBytesSize(Result);
          }
          if (Unknow0 != 0) {
            size += 1 + pb::CodedOutputStream.ComputeInt32Size(Unknow0);
          }
          if (Unknown1 != 0D) {
            size += 1 + 8;
          }
          if (Unknown2 != 0D) {
            size += 1 + 8;
          }
          if (Unknown3 != 0) {
            size += 1 + pb::CodedOutputStream.ComputeInt32Size(Unknown3);
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(QRScanResult other) {
          if (other == null) {
            return;
          }
          if (other.Result.Length != 0) {
            Result = other.Result;
          }
          if (other.Unknow0 != 0) {
            Unknow0 = other.Unknow0;
          }
          if (other.Unknown1 != 0D) {
            Unknown1 = other.Unknown1;
          }
          if (other.Unknown2 != 0D) {
            Unknown2 = other.Unknown2;
          }
          if (other.Unknown3 != 0) {
            Unknown3 = other.Unknown3;
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          input.ReadRawMessage(this);
        #else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 10: {
                Result = input.ReadBytes();
                break;
              }
              case 16: {
                Unknow0 = input.ReadInt32();
                break;
              }
              case 25: {
                Unknown1 = input.ReadDouble();
                break;
              }
              case 33: {
                Unknown2 = input.ReadDouble();
                break;
              }
              case 40: {
                Unknown3 = input.ReadInt32();
                break;
              }
            }
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                break;
              case 10: {
                Result = input.ReadBytes();
                break;
              }
              case 16: {
                Unknow0 = input.ReadInt32();
                break;
              }
              case 25: {
                Unknown1 = input.ReadDouble();
                break;
              }
              case 33: {
                Unknown2 = input.ReadDouble();
                break;
              }
              case 40: {
                Unknown3 = input.ReadInt32();
                break;
              }
            }
          }
        }
        #endif

      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
